version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - rkm
  - package-ecosystem: "maven"
    directory: "/integration"
    schedule:
      interval: "daily"
    reviewers:
      - rkm
