version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - SMI/reviewers
  - package-ecosystem: "maven"
    directory: "/integration"
    schedule:
      interval: "weekly"
    reviewers:
      - SMI/reviewers
