name: main

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set-up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: build all
        run: ./scripts/build/run-all.bash
      - name: compile, run basic test, and install
        run: mvn -B -ntp install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: set-up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: compile and run integration tests
        run: mvn -f integration/pom.xml -B -ntp test
  deploy:
    needs: test
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: check pom version set to tag
      #   run: ./.github/workflows/check-tag-pom-version-match.py
      - name: set-up JDK
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "temurin"
          cache: maven
      - name: build all
        run: ./scripts/build/run-all.bash
      - name: deploy
        run: mvn -X -B -ntp -DskipTests deploy
